import { PengajuanHargaItem } from './types';

export const INITIAL_PENGAJUAN_HARGA_ITEMS: PengajuanHargaItem[] = [
  {
    id: 'item-1',
    kode: 'SIP-001',
    kodeMaster: 'SIP-001-A-Keramik-60x60',
    item: 'Keramik',
    ukuran: '60x60',
    merk: 'Sandimas',
    warna: 'Grey',
    tipe: 'Siciily Grey',
    tebal: '9mm',
    permukaan: 'Matte',
    kategori: 'Pekerjaan Keramik',
    implementasi: 'Dinding',
    lokasi: 'Area Teras',
    informasiTambahan: 'Nat merk SIKA',
    deskripsiOtomatis: 'Keramik 60×60 Sandimas Grey Tipe Siciily Grey Matte Area Teras Nat merk SIKA (Dinding)',
    estimasiHarga: 185000,
    satuan: 'm2',
    status: 'DIAJUKAN',
    tanggalPengajuan: '2026-09-24',
  },
  {
    id: 'item-2',
    kode: 'SIP-002',
    kodeMaster: 'SIP-002-A-Keramik-60x60',
    item: 'Keramik',
    ukuran: '60x60',
    merk: 'Luxury',
    warna: 'White',
    tipe: 'Antique White',
    tebal: '9mm',
    permukaan: 'Polish',
    kategori: 'Pekerjaan Keramik',
    implementasi: 'Lantai',
    lokasi: 'Area Sales',
    informasiTambahan: 'Adhesive high-bond',
    deskripsiOtomatis: 'Keramik 60×60 Luxury White Tipe Antique White Polish Area Sales Semen high-bond (Lantai)',
    estimasiHarga: 195000,
    satuan: 'm2',
    status: 'DIAJUKAN',
    tanggalPengajuan: '2026-09-24',
  },
  {
    id: 'item-3',
    kode: 'SIP-003',
    kodeMaster: 'SIP-003-A-Keramik-60x60',
    item: 'Keramik',
    ukuran: '60x60',
    merk: 'Mahesa',
    warna: 'Cream',
    tipe: 'Cream Carolina',
    tebal: '9mm',
    permukaan: 'Double Loading',
    kategori: 'Pekerjaan Keramik',
    implementasi: 'Lantai',
    lokasi: 'Gudang',
    informasiTambahan: 'Beban racking pallet',
    deskripsiOtomatis: 'Keramik 60×60 Mahesa Cream Tipe Cream Carolina Double Loading Gudang Pallet (Lantai)',
    estimasiHarga: 210000,
    satuan: 'm2',
    status: 'DIAJUKAN',
    tanggalPengajuan: '2026-09-23',
  },
  {
    id: 'item-4',
    kode: 'SIP-004',
    kodeMaster: 'SIP-004-A-Keramik-60x60',
    item: 'Keramik',
    ukuran: '60x60',
    merk: 'Roman',
    warna: 'Green',
    tipe: 'Green Moss',
    tebal: '9mm',
    permukaan: 'Matte',
    kategori: 'Area Terbuka',
    implementasi: 'Dinding',
    lokasi: 'Selasar',
    informasiTambahan: 'Angkur fischer',
    deskripsiOtomatis: 'Keramik 60×60 Roman Green Tipe Green Moss Matte Selasar Angkur fischer (Dinding)',
    estimasiHarga: 225000,
    satuan: 'm2',
    status: 'DRAFT',
    tanggalPengajuan: '2026-09-22',
  },
  {
    id: 'item-5',
    kode: 'SIP-005',
    kodeMaster: 'SIP-005-A-Keramik-60x60',
    item: 'Keramik',
    ukuran: '60x60',
    merk: 'Roman',
    warna: 'White',
    tipe: 'Polish White',
    tebal: '9mm',
    permukaan: 'Polish',
    kategori: 'Pekerjaan Keramik',
    implementasi: 'Dinding',
    lokasi: 'Kamar Mandi',
    informasiTambahan: 'Waterproofing membran',
    deskripsiOtomatis: 'Keramik 60×60 Roman White Tipe Polish White Polish Kamar Mandi Waterproofing (Dinding)',
    estimasiHarga: 220000,
    satuan: 'm2',
    status: 'DIAJUKAN',
    tanggalPengajuan: '2026-09-21',
  },
  {
    id: 'item-6',
    kode: 'SIP-006',
    kodeMaster: 'SIP-006-A-Keramik-60x60',
    item: 'Keramik',
    ukuran: '60x60',
    merk: 'Indogress',
    warna: 'Black',
    tipe: 'Nero Portoro',
    tebal: '9mm',
    permukaan: 'Polish',
    kategori: 'Area Terbuka',
    implementasi: 'Dinding',
    lokasi: 'Fascia Depan',
    informasiTambahan: 'Bracket stainless',
    deskripsiOtomatis: 'Keramik 60×60 Indogress Black Tipe Nero Portoro Polish Fascia Depan Bracket stainless (Dinding)',
    estimasiHarga: 245000,
    satuan: 'm2',
    status: 'SIAP_SURVEI',
    tanggalPengajuan: '2026-09-20',
    koefisienUpahItems: [
      { id: 'u-1', label: 'Mandor', value: 0.0188, unit: 'Oh' },
      { id: 'u-2', label: 'Tukang', value: 0.1875, unit: 'Oh' },
      { id: 'u-3', label: 'Pekerja', value: 0.125, unit: 'Oh' },
    ],
    koefisienMaterialItems: [
      { id: 'm-1', label: 'Keramik', value: 1.034, unit: 'M2' },
      { id: 'm-2', label: 'Semen PC', value: 9.327, unit: 'Kg' },
      { id: 'm-3', label: 'Pasir', value: 0.0436, unit: 'M3' },
    ],
  },
  // Item Master Resmi Permanen (Aktif di Katalog Master Harga)
  {
    id: 'item-master-1',
    kode: 'SIP-007',
    kodeMaster: 'SIP-007-A-Granit-60x60',
    item: 'Granit Tile',
    ukuran: '60x60',
    merk: 'Granito',
    warna: 'Ivory Bone',
    tipe: 'Salsa Oasis',
    tebal: '10mm',
    permukaan: 'Nano Polish',
    kategori: 'Pekerjaan Lantai',
    implementasi: 'Lantai',
    lokasi: 'Area Kasir',
    informasiTambahan: 'Standar Toko Baru',
    deskripsiOtomatis: 'Granit Tile 60×60 Granito Ivory Bone Tipe Salsa Oasis Nano Polish Area Kasir (Lantai)',
    estimasiHarga: 265000,
    hargaRataRata: 265000,
    satuan: 'm2',
    status: 'RELEASED',
    tanggalPengajuan: '2026-08-15',
  },
  // Skenario Trial 1: Baru Diajukan S&B, Menunggu Approval B&M Regional Manager
  {
    id: 'item-trial-1',
    kode: 'SIP-008',
    kodeMaster: 'SIP-008-A-WPC-Wallpanel-20x290',
    item: 'WPC Wallpanel Fluted',
    ukuran: '20x290',
    merk: 'Duma',
    warna: 'Teak Wood',
    tipe: 'Linear Fluted 4-Groove',
    tebal: '12mm',
    permukaan: 'Embossed Woodgrain',
    kategori: 'Pekerjaan Dinding',
    implementasi: 'Dinding',
    lokasi: 'Area Point of Sale',
    informasiTambahan: 'Klip stainless dan lem sealant hybrid',
    deskripsiOtomatis: 'WPC Wallpanel Fluted 20×290 Duma Teak Wood Tipe Linear Fluted 4-Groove Embossed Woodgrain Area Point of Sale (Dinding)',
    estimasiHarga: 145000,
    hargaRataRata: 145000,
    satuan: 'batang',
    status: 'TRIAL_PENDING_REGIONAL_MGR',
    isTrial: true,
    alasanTrial: 'Uji coba aksen dinding display area kasir modern pengganti cat tekstur dengan ketahanan benturan tinggi.',
    tanggalPengajuan: '2026-09-27',
  },
  // Skenario Trial 2: Sedang Berjalan Aktif (Masa Sisa ~75 Hari)
  {
    id: 'item-trial-2',
    kode: 'SIP-009',
    kodeMaster: 'SIP-009-A-Cat-Epoxy-2-Komponen',
    item: 'Cat Lantai Epoxy Self-Leveling',
    ukuran: '20 Kg / Pail',
    merk: 'Propan',
    warna: 'Light Grey',
    tipe: 'Epogreen Multi-layer',
    tebal: '1000 Micron',
    permukaan: 'Gloss Anti-Slip',
    kategori: 'Pekerjaan Lantai',
    implementasi: 'Lantai',
    lokasi: 'Area Chiller & Gudang Basah',
    informasiTambahan: 'Primer moisture barrier',
    deskripsiOtomatis: 'Cat Lantai Epoxy Self-Leveling 20 Kg Propan Light Grey Tipe Epogreen Gloss Anti-Slip Gudang Basah (Lantai)',
    estimasiHarga: 320000,
    hargaRataRata: 320000,
    satuan: 'm2',
    status: 'TRIAL_RELEASED',
    isTrial: true,
    trialStartDate: '2026-09-13',
    trialDurationDays: 90,
    alasanTrial: 'Solusi lantai higienis tanpa nat untuk memangkas biaya maintenance keramik pecah di area beban tinggi.',
    tanggalPengajuan: '2026-09-10',
  },
  // Skenario Trial 3: Mendekati Batas Waktu 3 Bulan (Sisa ~5 Hari - PERLU TINDAKAN)
  {
    id: 'item-trial-3',
    kode: 'SIP-010',
    kodeMaster: 'SIP-010-A-Plafon-PVC-Wood-20x400',
    item: 'Plafon PVC Acoustic Water-Resistant',
    ukuran: '20x400',
    merk: 'Shunda Plafon',
    warna: 'White Matte',
    tipe: 'Hollow Anti-Sagging',
    tebal: '8mm',
    permukaan: 'Matte Flat',
    kategori: 'Pekerjaan Plafon',
    implementasi: 'Plafon',
    lokasi: 'Area Kanopi Teras',
    informasiTambahan: 'Rangka hollow galvalum 0.35',
    deskripsiOtomatis: 'Plafon PVC Acoustic 20×400 Shunda White Matte Tipe Hollow Anti-Sagging Area Kanopi Teras (Plafon)',
    estimasiHarga: 98000,
    hargaRataRata: 98000,
    satuan: 'm2',
    status: 'TRIAL_RELEASED',
    isTrial: true,
    trialStartDate: '2026-07-04',
    trialDurationDays: 90,
    alasanTrial: 'Pengganti kalsiboard luar ruang agar tahan tampias air hujan tanpa risiko lapuk dan jamur.',
    tanggalPengajuan: '2026-07-01',
  },
  // Skenario Trial 4: Sedang Proses Promosi Permanen ke Regional Manager (Phase 5)
  {
    id: 'item-trial-4',
    kode: 'SIP-011',
    kodeMaster: 'SIP-011-A-Lampu-LED-Batten-18W',
    item: 'Lampu LED Batten T8 Energy Saver',
    ukuran: '120 cm',
    merk: 'Philips',
    warna: 'Cool Daylight 6500K',
    tipe: 'Essential SmartBright',
    tebal: 'Standard',
    permukaan: 'Diffuser Polycarbonate',
    kategori: 'Pekerjaan Elektrikal',
    implementasi: 'Plafon',
    lokasi: 'Area Sales Utama',
    informasiTambahan: 'Garansi resmi 2 tahun',
    deskripsiOtomatis: 'Lampu LED Batten T8 120cm Philips Cool Daylight 6500K SmartBright Area Sales (Plafon)',
    estimasiHarga: 72500,
    hargaRataRata: 72500,
    satuan: 'unit',
    status: 'TRIAL_PROMOSI_REGIONAL_MGR',
    isTrial: true,
    trialStartDate: '2026-06-28',
    trialDurationDays: 90,
    trialEvaluationAction: 'PERMANEN',
    trialCatatanEvaluasi: 'Hasil evaluasi pilot 3 bulan di 5 toko: efisiensi konsumsi daya listrik turun 24% dan tingkat kerusakan 0%. Siap ditetapkan menjadi Master Resmi Permanen.',
    tanggalPengajuan: '2026-06-25',
  },
  // Skenario Trial 5: Perlu Revisi oleh S&B Specialist
  {
    id: 'item-trial-5',
    kode: 'SIP-016',
    kodeMaster: 'SIP-016-A-Cat-Silver-Ion-20L',
    item: 'Cat Dinding Antibakteri Silver Ion',
    ukuran: '20 Liter',
    merk: 'Mowilex',
    warna: 'White Lily',
    tipe: 'Silver Ion Shield',
    tebal: '2 Lapis',
    permukaan: 'Satin Eggshell',
    kategori: 'Pekerjaan Pengecatan',
    implementasi: 'Dinding Gerai',
    lokasi: 'Area Fresh Food & Chiller',
    toleransi: 'Daya sebar 12m2/L',
    informasiTambahan: 'Kadar VOC rendah ramah lingkungan',
    deskripsiOtomatis: 'Cat Dinding Antibakteri Silver Ion 20 Liter Mowilex White Lily Silver Ion Shield Area Fresh Food & Chiller (Dinding Gerai)',
    estimasiHarga: 1850000,
    hargaRataRata: 1850000,
    satuan: 'pail',
    status: 'TRIAL_REVISI',
    isTrial: true,
    alasanTrial: 'Pengujian daya tahan cat antibakteri untuk menekan bau dan jamur di area lembab.',
    tanggalPengajuan: '2026-09-26',
  },
  // Skenario Trial 6: Master Resmi Permanen Lolos Promosi Uji Coba
  {
    id: 'item-trial-6',
    kode: 'SIP-019',
    kodeMaster: 'SIP-019-A-Vinyl-HeavyDuty-3mm',
    item: 'Vinyl Flooring Plank Heavy Duty 3mm',
    ukuran: '15x90 cm',
    merk: 'Tarkett',
    warna: 'Natural Oak',
    tipe: 'Commercial Wear Layer 0.5mm',
    tebal: '3mm',
    permukaan: 'Deep Embossed Anti-Slip',
    kategori: 'Pekerjaan Lantai',
    implementasi: 'Lantai Gerai',
    lokasi: 'Area Bean Spot & Bakery',
    toleransi: '±0.1mm',
    informasiTambahan: 'Lem akrilik khusus vinyl komersial',
    deskripsiOtomatis: 'Vinyl Flooring Plank Heavy Duty 3mm 15×90 cm Tarkett Natural Oak Commercial Wear Layer Area Bean Spot & Bakery (Lantai Gerai)',
    estimasiHarga: 168000,
    hargaRataRata: 168000,
    satuan: 'm2',
    status: 'APPROVED_ACTIVE',
    isTrial: false,
    alasanTrial: 'Uji coba lantai estetik hangat area kafe Bean Spot dengan ketahanan tumpahan air/kopi.',
    trialCatatanEvaluasi: 'Lolos uji coba 3 bulan. Tahan gesekan troli dan tumpahan cairan tanpa noda atau mengelupas.',
    tanggalPengajuan: '2026-05-10',
  },
];
