import { PengajuanHargaItem } from './types';

export const INITIAL_PENGAJUAN_HARGA_ITEMS: PengajuanHargaItem[] = [
  {
    id: 'item-1',
    kode: 'SIP-001',
    kodeMaster: 'SIP-001-A-Keramik-60x60',
    item: 'Keramik',
    ukuran: '60x60',
    merk: 'Sandimas',
    warna: 'Grey',
    tipe: 'Siciily Grey',
    tebal: '9mm',
    permukaan: 'Matte',
    kategori: 'Pekerjaan Keramik',
    implementasi: 'Dinding',
    lokasi: 'Area Teras',
    informasiTambahan: 'Nat merk SIKA',
    deskripsiOtomatis: 'Keramik 60×60 Sandimas Grey Tipe Siciily Grey Matte Area Teras Nat merk SIKA (Dinding)',
    estimasiHarga: 185000,
    satuan: 'm2',
    status: 'DIAJUKAN',
    tanggalPengajuan: '2026-09-24',
  },
  {
    id: 'item-2',
    kode: 'SIP-002',
    kodeMaster: 'SIP-002-A-Keramik-60x60',
    item: 'Keramik',
    ukuran: '60x60',
    merk: 'Luxury',
    warna: 'White',
    tipe: 'Antique White',
    tebal: '9mm',
    permukaan: 'Polish',
    kategori: 'Pekerjaan Keramik',
    implementasi: 'Lantai',
    lokasi: 'Area Sales',
    informasiTambahan: 'Adhesive high-bond',
    deskripsiOtomatis: 'Keramik 60×60 Luxury White Tipe Antique White Polish Area Sales Semen high-bond (Lantai)',
    estimasiHarga: 195000,
    satuan: 'm2',
    status: 'DIAJUKAN',
    tanggalPengajuan: '2026-09-24',
  },
  {
    id: 'item-3',
    kode: 'SIP-003',
    kodeMaster: 'SIP-003-A-Keramik-60x60',
    item: 'Keramik',
    ukuran: '60x60',
    merk: 'Mahesa',
    warna: 'Cream',
    tipe: 'Cream Carolina',
    tebal: '9mm',
    permukaan: 'Double Loading',
    kategori: 'Pekerjaan Keramik',
    implementasi: 'Lantai',
    lokasi: 'Gudang',
    informasiTambahan: 'Beban racking pallet',
    deskripsiOtomatis: 'Keramik 60×60 Mahesa Cream Tipe Cream Carolina Double Loading Gudang Pallet (Lantai)',
    estimasiHarga: 210000,
    satuan: 'm2',
    status: 'DIAJUKAN',
    tanggalPengajuan: '2026-09-23',
  },
  {
    id: 'item-4',
    kode: 'SIP-004',
    kodeMaster: 'SIP-004-A-Keramik-60x60',
    item: 'Keramik',
    ukuran: '60x60',
    merk: 'Roman',
    warna: 'Green',
    tipe: 'Green Moss',
    tebal: '9mm',
    permukaan: 'Matte',
    kategori: 'Area Terbuka',
    implementasi: 'Dinding',
    lokasi: 'Selasar',
    informasiTambahan: 'Angkur fischer',
    deskripsiOtomatis: 'Keramik 60×60 Roman Green Tipe Green Moss Matte Selasar Angkur fischer (Dinding)',
    estimasiHarga: 225000,
    satuan: 'm2',
    status: 'DRAFT',
    tanggalPengajuan: '2026-09-22',
  },
  {
    id: 'item-5',
    kode: 'SIP-005',
    kodeMaster: 'SIP-005-A-Keramik-60x60',
    item: 'Keramik',
    ukuran: '60x60',
    merk: 'Roman',
    warna: 'White',
    tipe: 'Polish White',
    tebal: '9mm',
    permukaan: 'Polish',
    kategori: 'Pekerjaan Keramik',
    implementasi: 'Dinding',
    lokasi: 'Kamar Mandi',
    informasiTambahan: 'Waterproofing membran',
    deskripsiOtomatis: 'Keramik 60×60 Roman White Tipe Polish White Polish Kamar Mandi Waterproofing (Dinding)',
    estimasiHarga: 220000,
    satuan: 'm2',
    status: 'DIAJUKAN',
    tanggalPengajuan: '2026-09-21',
  },
  {
    id: 'item-6',
    kode: 'SIP-006',
    kodeMaster: 'SIP-006-A-Keramik-60x60',
    item: 'Keramik',
    ukuran: '60x60',
    merk: 'Indogress',
    warna: 'Black',
    tipe: 'Nero Portoro',
    tebal: '9mm',
    permukaan: 'Polish',
    kategori: 'Area Terbuka',
    implementasi: 'Dinding',
    lokasi: 'Fascia Depan',
    informasiTambahan: 'Bracket stainless',
    deskripsiOtomatis: 'Keramik 60×60 Indogress Black Tipe Nero Portoro Polish Fascia Depan Bracket stainless (Dinding)',
    estimasiHarga: 245000,
    satuan: 'm2',
    status: 'DISETUJUI',
    tanggalPengajuan: '2026-09-20',
  },
];
